#!/usr/bin/env python

"""
Script to output the absolute path of a file.

This is very similar to "readlink -f" but I'm used to this now.

Author: Matt Hillsdon <matt@hillsdon.net>
"""

import os
import sys

USAGE="Usage: abspath <f1>...<fn>"

if __name__ == "__main__":
    args = sys.argv[1:]
    if "-h" in args or "--help" in args:
        print USAGE
        sys.exit(0)

    if len(args) == 0:
        args = ["."]
    for a in args:
        print os.path.abspath(a)
