#!/usr/bin/env python

from __future__ import with_statement

import sys

USAGE="""Usage: linlen <LENGTH> <FILE>
       The default length is 80.
"""

if __name__ == "__main__":
    args = sys.argv[1:]
    if "-h" in args or "--help" in args:
        print USAGE
        sys.exit(0)
    if len(args) == 0:
        print >>sys.stderr, USAGE
        sys.exit(1)
    try:
        limit = 80 if len(args) == 1 else int(args[0])
    except ValueError:
        print >>sys.stderr, "Invalid line length"
        sys.exit(1)
        
    line = 1
    failures = 0
    with open(args[-1], "rU") as fin:
        for l in fin:
            l = l.rstrip("\n")
            length = len(l)   
            if length > limit:
                failures = failures + 1
                print "%d: %s" % (length, l)
        line = line + 1
    sys.exit(2 if failures else 0)


