#!/usr/bin/env python

"""
Script to output the directory corresponding to a Java package.

Exit codes: 1 - args
            2 - no dir found

Author: Matt Hillsdon <matt@hillsdon.net>
"""

import os
import sys

USAGE="Usage: pdir <package>"

if __name__ == "__main__":
    args = sys.argv[1:]
    if "-h" in args or "--help" in args:
        print USAGE
        sys.exit(0)
    if len(args) != 1:
        print >> sys.stderr, USAGE
        sys.exit(1)
    pkg = args[0]
    path = os.path.join(*pkg.split("."))
    # This could be generalised, but this order is useful to me.
    for prefix in ["", "src", "unitTests/src", "functionalTests/src"]:
        full_path = os.path.join(prefix, path)
        if os.path.isdir(full_path):
            print full_path
            sys.exit(0)
    sys.exit(2)
