#!/bin/bash
# Script to stop zip files spewing crap everywhere.
#
# mth 2005-07-20.

function die {
  echo $1
  exit 1
}

# If the zip contains more than one root file/directory
# then create a directory for it using the zip name minus
# the extension.

if [[ `zipinfo -1 $1 | cut -f 1 -d / | uniq | wc -l` > 1 ]]; 
then
  DIR=${1%.[^.]*}
  PREF="../"
  mkdir $DIR
  if [ "$?" -ne 0 ]
  then
    die "Failed to create $DIR, please unzip manually".
  fi
else
  PREF="./"
  DIR="."
fi

pushd $DIR
unzip $PREF$1
popd

